export default [
  {
    id: 1,
    name: 'Defence',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/d6198b80-f048-4514-be87-d485b40361ea.png',
    imageLicence: 'CC',
  },
  {
    id: 2,
    name: 'State Finance',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/be5ebfed-b323-4601-ab48-8c71d2916f50.png',
  },
  {
    id: 3,
    name: 'University Education',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/fcaa9595-8db1-43e3-8f7a-5575ead0efa9.png',
  },
  {
    id: 4,
    name: 'School Education',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/5dc3f913-f84c-4143-a1a5-5ee695c775cc.png',
  },
  {
    id: 5,
    name: 'Mining',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/a85d0bf7-353b-451c-8d8c-1faf34e01ac0.png',
    imageLicence: 'CC',
  },
  {
    id: 6,
    name: 'Space',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/bb5cfd57-cb8d-47e5-af0b-06e593ba1aed.png',
    imageLicence: 'CC',
  },
  {
    id: 7,
    name: 'Agriculture',
    institutionOwnershipLevels: ['UNION', 'STATE'],
    lawMakingLevels: ['STATE'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/b26b273f-41e1-44fd-a86d-463d0e617576.png',
    imageLicence: 'CC',
  },
  {
    id: 8,
    name: 'Atomic Energy',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/35bb0111-9588-4e77-9dba-2f21077cd246.png',
  },
  {
    id: 9,
    name: 'Foreign Affairs',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/ecebf5b0-7105-45d8-8a3e-50a73e04193f.png',
  },
  {
    id: 10,
    name: 'Railways',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/30960e08-4b62-4f67-b74c-d3b664aea789.png',
    imageLicence: 'CC',
  },
  {
    id: 11,
    name: 'Technical and Scientific Education',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/9c5e4c30-e637-4d67-a5ce-9f037f581ae2.png',
  },
  {
    id: 12,
    name: 'Public Debt',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/1a5a043a-d332-4a7d-b51f-984fa2a373df.png',
  },
  {
    id: 13,
    name: 'Road Transport and Highways',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/92fcc863-331d-4c4e-86bf-dde6c60ac17d.png',
    imageLicence: 'CC',
  },
  {
    id: 14,
    name: 'Ports and Shipping',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/5675e1d6-2a01-46c1-b600-004decfa7e58.png',
    imageLicence: 'CC',
  },
  {
    id: 15,
    name: 'Civil Aviation',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/c339d659-8e34-4b1f-82fb-bb6d4cf453aa.png',
    imageLicence: 'CC',
  },
  {
    id: 16,
    name: 'Communication',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/ff1e0184-3198-437c-a6b8-3e6a03aae249.png',
  },
  {
    id: 17,
    name: 'Banking and Insurance',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/639a3f58-503f-4613-a6d9-89a59e582661.png',
  },
  {
    id: 18,
    name: 'Petroleum and Natural Gas',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/25d83e01-74f7-4f24-863e-83a2bee23fd4.png',
    imageLicence: 'CC',
  },
  {
    id: 19,
    name: 'Elections',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/3e5357f5-6583-4f81-b3ee-1955d34a1151.png',
    imageLicence: 'CC',
  },
  {
    id: 20,
    name: 'Law Enforcement',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/1c82b600-1518-4ce4-b335-a166f2971003.png',
  },
  {
    id: 21,
    name: 'Healthcare',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/8b23426f-e6dd-4fb0-a73b-24bc8b98b625.png',
    imageLicence: 'CC',
  },
  {
    id: 22,
    name: 'National and International Trade',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/40d38850-d7d4-4a09-9699-7747b2e5307b.png',
  },
  {
    id: 23,
    name: 'Industries And Enterprises',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/7be1e6e2-1b13-47ba-9a7d-68c51bf8ae82.png',
  },
  {
    id: 24,
    name: 'Taxes and Duties',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/5295ea59-9c70-4c9d-a170-667889b7d093.png',
    imageLicence: 'CC',
  },
  {
    id: 25,
    name: 'Inquiries and Committies',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/04fadf65-ef12-489d-99ca-77a84ad6ab97.png',
    imageLicence: 'CC',
  },
  {
    id: 26,
    name: 'Census, Surveys and Statistics',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/35e0cc08-013f-469b-a0e9-a7062b417654.png',
    imageLicence: 'CC',
  },
  {
    id: 27,
    name: 'Stock exchanges and futures markets',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/e0552249-9a92-4c9c-acf9-f18dc02cd856.png',
  },
  {
    id: 28,
    name: 'History and Culture',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/02abaac9-1061-4d30-8b69-dc71b029cc58.png',
  },
  {
    id: 29,
    name: 'Staff Selection and Training',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/bbef148c-50bb-4ebd-8ee4-3d7b53cf2b64.png',
  },
  {
    id: 30,
    name: 'Audit of Union and State Accounts',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/d1d4c13b-ef6b-41e1-ad5c-c669856be296.png',
  },
  {
    id: 31,
    name: 'Salaries and Pensions',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/e4aa8603-5f0e-4522-9b33-9194225df67e.png',
  },
  {
    id: 32,
    name: 'Labour and Employment',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/d59cce96-0f26-406c-aa9a-ecc20b957a9b.png',
  },
  {
    id: 33,
    name: 'Judiciary',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://dev-qbila-images.s3.amazonaws.com/093c6d6f-4f1e-459c-87fb-fc0d4c89482f.png',
  },
  {
    id: 34,
    name: 'Media and Censorship',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Supreme_Court_of_India%2C_inside_view_07.jpg',
  },
  {
    id: 35,
    name: 'Information Technology',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Supreme_Court_of_India%2C_inside_view_07.jpg',
  },
  {
    id: 36,
    name: 'Fishing',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Supreme_Court_of_India%2C_inside_view_07.jpg',
  },
  {
    id: 37,
    name: 'Parliament and State Assemblies',
    institutionOwnershipLevels: ['UNION'],
    lawMakingLevels: ['UNION'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Supreme_Court_of_India%2C_inside_view_07.jpg',
  },
];
